### ISSUE TITLE
Assumption of having inputs with even size features

### ISSUE THREAD

**Issue by Farzin-Negahbani** [FirstHandScientist/genhmm#7]
Hi, 

Thanks for sharing your code.  I am adapting your code on my own dataset with different pre-processing and I faced the following issue:
As mentioned in "_chunk" function of realnvp.py you have an assumption of equal size chunks that means the input feature dimension should be even. One way around this limitation is padding features with 0 but I was wondering would it affect the logic behind the method? or do you have any other suggestions for this issue?

**Comment by FirstHandScientist** [comment]
Hey,
Thank you for your interests.
Yes, padding zeros is straightforward solution for old dimension vectors. Actually, it does not affect the logic behind it. In each flow step,  half of your hidden states are kept without change while the other half get updated (how this update should be depends on the other half hidden states via a neural network mapping). Padding zero is only to make the implementation easier, i.e. to re-use the same articheture of the mentioned neural network mapping for each flow block.
If you do not pad zero to get even dimension vector, you may need to customize the neural network mapping for each flow block to implement the flow model. 

If you do not want to pad zero, you can define two types of nerual network mappings for each flow block to model to two-directional mappings from one chunk to another chunk.

There are other flow models:
1. Inverse auto-regressive flow (IAF) proposed in _Danilo Jimenez Rezende and Shakir Mohamed. Variational inference with
normalizing flows. arXiv, 2015._
2. ordinary differential equation: _Ricky T. Q. Chen, Yulia Rubanova, Jesse Bettencourt, and David K Du-
venaud. Neural ordinary differential equations. In Advances in Neural In-
formation Processing Systems 31, pages 6571–6583_

**Comment by Farzin-Negahbani** [comment]
Great! thank you for your comprehensive explanation.
